//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum BillboardType {
  BBT_POINT,
  BBT_ORIENTED_COMMON,
  BBT_ORIENTED_SELF,
  BBT_PERPENDICULAR_COMMON,
  BBT_PERPENDICULAR_SELF
}

}
