//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum CompareFunction : byte {
  CMPF_ALWAYS_FAIL,
  CMPF_ALWAYS_PASS,
  CMPF_LESS,
  CMPF_LESS_EQUAL,
  CMPF_EQUAL,
  CMPF_NOT_EQUAL,
  CMPF_GREATER_EQUAL,
  CMPF_GREATER
}

}
