//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ConcreteNodeType {
  CNT_VARIABLE,
  CNT_VARIABLE_ASSIGN,
  CNT_WORD,
  CNT_IMPORT,
  CNT_QUOTE,
  CNT_LBRACE,
  CNT_RBRACE,
  CNT_COLON
}

}
