//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum CullingMode : byte {
  CULL_NONE = 1,
  CULL_CLOCKWISE = 2,
  CULL_ANTICLOCKWISE = 3
}

}
