//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum FilterOptions : byte {
  FO_NONE,
  FO_POINT,
  FO_LINEAR,
  FO_ANISOTROPIC
}

}
