//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum GpuParamVariability : ushort {
  GPV_GLOBAL = 1,
  GPV_PER_OBJECT = 2,
  GPV_LIGHTS = 4,
  GPV_PASS_ITERATION_NUMBER = 8,
  GPV_ALL = 0xFFFF
}

}
