//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum GpuProgramType : byte {
  GPT_VERTEX_PROGRAM = 0,
  GPT_FRAGMENT_PROGRAM,
  GPT_GEOMETRY_PROGRAM,
  GPT_DOMAIN_PROGRAM,
  GPT_HULL_PROGRAM,
  GPT_MESH_PROGRAM,
  GPT_COMPUTE_PROGRAM,
  GPT_TASK_PROGRAM
}

}
