//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImDrawFlags_ {
  ImDrawFlags_None = 0,
  ImDrawFlags_Closed = 1 << 0,
  ImDrawFlags_RoundCornersTopLeft = 1 << 4,
  ImDrawFlags_RoundCornersTopRight = 1 << 5,
  ImDrawFlags_RoundCornersBottomLeft = 1 << 6,
  ImDrawFlags_RoundCornersBottomRight = 1 << 7,
  ImDrawFlags_RoundCornersNone = 1 << 8,
  ImDrawFlags_RoundCornersTop = ImDrawFlags_RoundCornersTopLeft|ImDrawFlags_RoundCornersTopRight,
  ImDrawFlags_RoundCornersBottom = ImDrawFlags_RoundCornersBottomLeft|ImDrawFlags_RoundCornersBottomRight,
  ImDrawFlags_RoundCornersLeft = ImDrawFlags_RoundCornersBottomLeft|ImDrawFlags_RoundCornersTopLeft,
  ImDrawFlags_RoundCornersRight = ImDrawFlags_RoundCornersBottomRight|ImDrawFlags_RoundCornersTopRight,
  ImDrawFlags_RoundCornersAll = ImDrawFlags_RoundCornersTopLeft|ImDrawFlags_RoundCornersTopRight|ImDrawFlags_RoundCornersBottomLeft|ImDrawFlags_RoundCornersBottomRight,
  ImDrawFlags_RoundCornersDefault_ = ImDrawFlags_RoundCornersAll,
  ImDrawFlags_RoundCornersMask_ = ImDrawFlags_RoundCornersAll|ImDrawFlags_RoundCornersNone
}

}
