//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ImFontGlyph : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImFontGlyph(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImFontGlyph obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImFontGlyph obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImFontGlyph() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImGuiPINVOKE.delete_ImFontGlyph(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Colored {
    set {
      ImGuiPINVOKE.ImFontGlyph_Colored_set(swigCPtr, value);
    } 
    get {
      uint ret = ImGuiPINVOKE.ImFontGlyph_Colored_get(swigCPtr);
      return ret;
    } 
  }

  public uint Visible {
    set {
      ImGuiPINVOKE.ImFontGlyph_Visible_set(swigCPtr, value);
    } 
    get {
      uint ret = ImGuiPINVOKE.ImFontGlyph_Visible_get(swigCPtr);
      return ret;
    } 
  }

  public uint Codepoint {
    set {
      ImGuiPINVOKE.ImFontGlyph_Codepoint_set(swigCPtr, value);
    } 
    get {
      uint ret = ImGuiPINVOKE.ImFontGlyph_Codepoint_get(swigCPtr);
      return ret;
    } 
  }

  public float AdvanceX {
    set {
      ImGuiPINVOKE.ImFontGlyph_AdvanceX_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_AdvanceX_get(swigCPtr);
      return ret;
    } 
  }

  public float X0 {
    set {
      ImGuiPINVOKE.ImFontGlyph_X0_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_X0_get(swigCPtr);
      return ret;
    } 
  }

  public float Y0 {
    set {
      ImGuiPINVOKE.ImFontGlyph_Y0_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_Y0_get(swigCPtr);
      return ret;
    } 
  }

  public float X1 {
    set {
      ImGuiPINVOKE.ImFontGlyph_X1_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_X1_get(swigCPtr);
      return ret;
    } 
  }

  public float Y1 {
    set {
      ImGuiPINVOKE.ImFontGlyph_Y1_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_Y1_get(swigCPtr);
      return ret;
    } 
  }

  public float U0 {
    set {
      ImGuiPINVOKE.ImFontGlyph_U0_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_U0_get(swigCPtr);
      return ret;
    } 
  }

  public float V0 {
    set {
      ImGuiPINVOKE.ImFontGlyph_V0_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_V0_get(swigCPtr);
      return ret;
    } 
  }

  public float U1 {
    set {
      ImGuiPINVOKE.ImFontGlyph_U1_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_U1_get(swigCPtr);
      return ret;
    } 
  }

  public float V1 {
    set {
      ImGuiPINVOKE.ImFontGlyph_V1_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImFontGlyph_V1_get(swigCPtr);
      return ret;
    } 
  }

  public ImFontGlyph() : this(ImGuiPINVOKE.new_ImFontGlyph(), true) {
  }

}

}
