//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ImGuiKeyData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImGuiKeyData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImGuiKeyData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImGuiKeyData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImGuiKeyData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImGuiPINVOKE.delete_ImGuiKeyData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool Down {
    set {
      ImGuiPINVOKE.ImGuiKeyData_Down_set(swigCPtr, value);
    } 
    get {
      bool ret = ImGuiPINVOKE.ImGuiKeyData_Down_get(swigCPtr);
      return ret;
    } 
  }

  public float DownDuration {
    set {
      ImGuiPINVOKE.ImGuiKeyData_DownDuration_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImGuiKeyData_DownDuration_get(swigCPtr);
      return ret;
    } 
  }

  public float DownDurationPrev {
    set {
      ImGuiPINVOKE.ImGuiKeyData_DownDurationPrev_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImGuiKeyData_DownDurationPrev_get(swigCPtr);
      return ret;
    } 
  }

  public float AnalogValue {
    set {
      ImGuiPINVOKE.ImGuiKeyData_AnalogValue_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImGuiKeyData_AnalogValue_get(swigCPtr);
      return ret;
    } 
  }

  public ImGuiKeyData() : this(ImGuiPINVOKE.new_ImGuiKeyData(), true) {
  }

}

}
