//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiItemFlags_ {
  ImGuiItemFlags_None = 0,
  ImGuiItemFlags_NoTabStop = 1 << 0,
  ImGuiItemFlags_NoNav = 1 << 1,
  ImGuiItemFlags_NoNavDefaultFocus = 1 << 2,
  ImGuiItemFlags_ButtonRepeat = 1 << 3,
  ImGuiItemFlags_AutoClosePopups = 1 << 4,
  ImGuiItemFlags_AllowDuplicateId = 1 << 5
}

}
