//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ImGuiSelectionExternalStorage : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImGuiSelectionExternalStorage(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImGuiSelectionExternalStorage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImGuiSelectionExternalStorage obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImGuiSelectionExternalStorage() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImGuiPINVOKE.delete_ImGuiSelectionExternalStorage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_void UserData {
    set {
      ImGuiPINVOKE.ImGuiSelectionExternalStorage_UserData_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ImGuiPINVOKE.ImGuiSelectionExternalStorage_UserData_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_ImGuiSelectionExternalStorage_int_bool__void AdapterSetItemSelected {
    set {
      ImGuiPINVOKE.ImGuiSelectionExternalStorage_AdapterSetItemSelected_set(swigCPtr, SWIGTYPE_p_f_p_ImGuiSelectionExternalStorage_int_bool__void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ImGuiPINVOKE.ImGuiSelectionExternalStorage_AdapterSetItemSelected_get(swigCPtr);
      SWIGTYPE_p_f_p_ImGuiSelectionExternalStorage_int_bool__void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_ImGuiSelectionExternalStorage_int_bool__void(cPtr, false);
      return ret;
    } 
  }

  public ImGuiSelectionExternalStorage() : this(ImGuiPINVOKE.new_ImGuiSelectionExternalStorage(), true) {
  }

  public void ApplyRequests(ImGuiMultiSelectIO ms_io) {
    ImGuiPINVOKE.ImGuiSelectionExternalStorage_ApplyRequests(swigCPtr, ImGuiMultiSelectIO.getCPtr(ms_io));
  }

}

}
