//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ImGuiPayload : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImGuiPayload(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImGuiPayload obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImGuiPayload obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImGuiPayload() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImGuiPINVOKE.delete_ImGuiPayload(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_void Data {
    set {
      ImGuiPINVOKE.ImGuiPayload_Data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ImGuiPINVOKE.ImGuiPayload_Data_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public int DataSize {
    set {
      ImGuiPINVOKE.ImGuiPayload_DataSize_set(swigCPtr, value);
    } 
    get {
      int ret = ImGuiPINVOKE.ImGuiPayload_DataSize_get(swigCPtr);
      return ret;
    } 
  }

  public uint SourceId {
    set {
      ImGuiPINVOKE.ImGuiPayload_SourceId_set(swigCPtr, value);
    } 
    get {
      uint ret = ImGuiPINVOKE.ImGuiPayload_SourceId_get(swigCPtr);
      return ret;
    } 
  }

  public uint SourceParentId {
    set {
      ImGuiPINVOKE.ImGuiPayload_SourceParentId_set(swigCPtr, value);
    } 
    get {
      uint ret = ImGuiPINVOKE.ImGuiPayload_SourceParentId_get(swigCPtr);
      return ret;
    } 
  }

  public int DataFrameCount {
    set {
      ImGuiPINVOKE.ImGuiPayload_DataFrameCount_set(swigCPtr, value);
    } 
    get {
      int ret = ImGuiPINVOKE.ImGuiPayload_DataFrameCount_get(swigCPtr);
      return ret;
    } 
  }

  public string DataType {
    set {
      ImGuiPINVOKE.ImGuiPayload_DataType_set(swigCPtr, value);
    } 
    get {
      string ret = ImGuiPINVOKE.ImGuiPayload_DataType_get(swigCPtr);
      return ret;
    } 
  }

  public bool Preview {
    set {
      ImGuiPINVOKE.ImGuiPayload_Preview_set(swigCPtr, value);
    } 
    get {
      bool ret = ImGuiPINVOKE.ImGuiPayload_Preview_get(swigCPtr);
      return ret;
    } 
  }

  public bool Delivery {
    set {
      ImGuiPINVOKE.ImGuiPayload_Delivery_set(swigCPtr, value);
    } 
    get {
      bool ret = ImGuiPINVOKE.ImGuiPayload_Delivery_get(swigCPtr);
      return ret;
    } 
  }

  public ImGuiPayload() : this(ImGuiPINVOKE.new_ImGuiPayload(), true) {
  }

  public void Clear() {
    ImGuiPINVOKE.ImGuiPayload_Clear(swigCPtr);
  }

  public bool IsDataType(string type) {
    bool ret = ImGuiPINVOKE.ImGuiPayload_IsDataType(swigCPtr, type);
    return ret;
  }

  public bool IsPreview() {
    bool ret = ImGuiPINVOKE.ImGuiPayload_IsPreview(swigCPtr);
    return ret;
  }

  public bool IsDelivery() {
    bool ret = ImGuiPINVOKE.ImGuiPayload_IsDelivery(swigCPtr);
    return ret;
  }

}

}
