//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiTableColumnFlags_ {
  ImGuiTableColumnFlags_None = 0,
  ImGuiTableColumnFlags_Disabled = 1 << 0,
  ImGuiTableColumnFlags_DefaultHide = 1 << 1,
  ImGuiTableColumnFlags_DefaultSort = 1 << 2,
  ImGuiTableColumnFlags_WidthStretch = 1 << 3,
  ImGuiTableColumnFlags_WidthFixed = 1 << 4,
  ImGuiTableColumnFlags_NoResize = 1 << 5,
  ImGuiTableColumnFlags_NoReorder = 1 << 6,
  ImGuiTableColumnFlags_NoHide = 1 << 7,
  ImGuiTableColumnFlags_NoClip = 1 << 8,
  ImGuiTableColumnFlags_NoSort = 1 << 9,
  ImGuiTableColumnFlags_NoSortAscending = 1 << 10,
  ImGuiTableColumnFlags_NoSortDescending = 1 << 11,
  ImGuiTableColumnFlags_NoHeaderLabel = 1 << 12,
  ImGuiTableColumnFlags_NoHeaderWidth = 1 << 13,
  ImGuiTableColumnFlags_PreferSortAscending = 1 << 14,
  ImGuiTableColumnFlags_PreferSortDescending = 1 << 15,
  ImGuiTableColumnFlags_IndentEnable = 1 << 16,
  ImGuiTableColumnFlags_IndentDisable = 1 << 17,
  ImGuiTableColumnFlags_AngledHeader = 1 << 18,
  ImGuiTableColumnFlags_IsEnabled = 1 << 24,
  ImGuiTableColumnFlags_IsVisible = 1 << 25,
  ImGuiTableColumnFlags_IsSorted = 1 << 26,
  ImGuiTableColumnFlags_IsHovered = 1 << 27,
  ImGuiTableColumnFlags_WidthMask_ = ImGuiTableColumnFlags_WidthStretch|ImGuiTableColumnFlags_WidthFixed,
  ImGuiTableColumnFlags_IndentMask_ = ImGuiTableColumnFlags_IndentEnable|ImGuiTableColumnFlags_IndentDisable,
  ImGuiTableColumnFlags_StatusMask_ = ImGuiTableColumnFlags_IsEnabled|ImGuiTableColumnFlags_IsVisible|ImGuiTableColumnFlags_IsSorted|ImGuiTableColumnFlags_IsHovered,
  ImGuiTableColumnFlags_NoDirectResize_ = 1 << 30
}

}
