//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiMultiSelectFlags_ {
  ImGuiMultiSelectFlags_None = 0,
  ImGuiMultiSelectFlags_SingleSelect = 1 << 0,
  ImGuiMultiSelectFlags_NoSelectAll = 1 << 1,
  ImGuiMultiSelectFlags_NoRangeSelect = 1 << 2,
  ImGuiMultiSelectFlags_NoAutoSelect = 1 << 3,
  ImGuiMultiSelectFlags_NoAutoClear = 1 << 4,
  ImGuiMultiSelectFlags_NoAutoClearOnReselect = 1 << 5,
  ImGuiMultiSelectFlags_BoxSelect1d = 1 << 6,
  ImGuiMultiSelectFlags_BoxSelect2d = 1 << 7,
  ImGuiMultiSelectFlags_BoxSelectNoScroll = 1 << 8,
  ImGuiMultiSelectFlags_ClearOnEscape = 1 << 9,
  ImGuiMultiSelectFlags_ClearOnClickVoid = 1 << 10,
  ImGuiMultiSelectFlags_ScopeWindow = 1 << 11,
  ImGuiMultiSelectFlags_ScopeRect = 1 << 12,
  ImGuiMultiSelectFlags_SelectOnClick = 1 << 13,
  ImGuiMultiSelectFlags_SelectOnClickRelease = 1 << 14,
  ImGuiMultiSelectFlags_NavWrapX = 1 << 16
}

}
