//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiPopupFlags_ {
  ImGuiPopupFlags_None = 0,
  ImGuiPopupFlags_MouseButtonLeft = 0,
  ImGuiPopupFlags_MouseButtonRight = 1,
  ImGuiPopupFlags_MouseButtonMiddle = 2,
  ImGuiPopupFlags_MouseButtonMask_ = 0x1F,
  ImGuiPopupFlags_MouseButtonDefault_ = 1,
  ImGuiPopupFlags_NoReopen = 1 << 5,
  ImGuiPopupFlags_NoOpenOverExistingPopup = 1 << 7,
  ImGuiPopupFlags_NoOpenOverItems = 1 << 8,
  ImGuiPopupFlags_AnyPopupId = 1 << 10,
  ImGuiPopupFlags_AnyPopupLevel = 1 << 11,
  ImGuiPopupFlags_AnyPopup = ImGuiPopupFlags_AnyPopupId|ImGuiPopupFlags_AnyPopupLevel
}

}
