//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiFocusedFlags_ {
  ImGuiFocusedFlags_None = 0,
  ImGuiFocusedFlags_ChildWindows = 1 << 0,
  ImGuiFocusedFlags_RootWindow = 1 << 1,
  ImGuiFocusedFlags_AnyWindow = 1 << 2,
  ImGuiFocusedFlags_NoPopupHierarchy = 1 << 3,
  ImGuiFocusedFlags_RootAndChildWindows = ImGuiFocusedFlags_RootWindow|ImGuiFocusedFlags_ChildWindows
}

}
