//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiInputFlags_ {
  ImGuiInputFlags_None = 0,
  ImGuiInputFlags_Repeat = 1 << 0,
  ImGuiInputFlags_RouteActive = 1 << 10,
  ImGuiInputFlags_RouteFocused = 1 << 11,
  ImGuiInputFlags_RouteGlobal = 1 << 12,
  ImGuiInputFlags_RouteAlways = 1 << 13,
  ImGuiInputFlags_RouteOverFocused = 1 << 14,
  ImGuiInputFlags_RouteOverActive = 1 << 15,
  ImGuiInputFlags_RouteUnlessBgFocused = 1 << 16,
  ImGuiInputFlags_RouteFromRootWindow = 1 << 17,
  ImGuiInputFlags_Tooltip = 1 << 18
}

}
