//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiViewportFlags_ {
  ImGuiViewportFlags_None = 0,
  ImGuiViewportFlags_IsPlatformWindow = 1 << 0,
  ImGuiViewportFlags_IsPlatformMonitor = 1 << 1,
  ImGuiViewportFlags_OwnedByApp = 1 << 2
}

}
