//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiTabBarFlags_ {
  ImGuiTabBarFlags_None = 0,
  ImGuiTabBarFlags_Reorderable = 1 << 0,
  ImGuiTabBarFlags_AutoSelectNewTabs = 1 << 1,
  ImGuiTabBarFlags_TabListPopupButton = 1 << 2,
  ImGuiTabBarFlags_NoCloseWithMiddleMouseButton = 1 << 3,
  ImGuiTabBarFlags_NoTabListScrollingButtons = 1 << 4,
  ImGuiTabBarFlags_NoTooltip = 1 << 5,
  ImGuiTabBarFlags_DrawSelectedOverline = 1 << 6,
  ImGuiTabBarFlags_FittingPolicyResizeDown = 1 << 7,
  ImGuiTabBarFlags_FittingPolicyScroll = 1 << 8,
  ImGuiTabBarFlags_FittingPolicyMask_ = ImGuiTabBarFlags_FittingPolicyResizeDown|ImGuiTabBarFlags_FittingPolicyScroll,
  ImGuiTabBarFlags_FittingPolicyDefault_ = ImGuiTabBarFlags_FittingPolicyResizeDown
}

}
