//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ImGuiStoragePair : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImGuiStoragePair(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImGuiStoragePair obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImGuiStoragePair obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImGuiStoragePair() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImGuiPINVOKE.delete_ImGuiStoragePair(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint key {
    set {
      ImGuiPINVOKE.ImGuiStoragePair_key_set(swigCPtr, value);
    } 
    get {
      uint ret = ImGuiPINVOKE.ImGuiStoragePair_key_get(swigCPtr);
      return ret;
    } 
  }

  public int val_i {
    set {
      ImGuiPINVOKE.ImGuiStoragePair_val_i_set(swigCPtr, value);
    } 
    get {
      int ret = ImGuiPINVOKE.ImGuiStoragePair_val_i_get(swigCPtr);
      return ret;
    } 
  }

  public float val_f {
    set {
      ImGuiPINVOKE.ImGuiStoragePair_val_f_set(swigCPtr, value);
    } 
    get {
      float ret = ImGuiPINVOKE.ImGuiStoragePair_val_f_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void val_p {
    set {
      ImGuiPINVOKE.ImGuiStoragePair_val_p_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ImGuiPINVOKE.ImGuiStoragePair_val_p_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public ImGuiStoragePair(uint _key, int _val) : this(ImGuiPINVOKE.new_ImGuiStoragePair__SWIG_0(_key, _val), true) {
  }

  public ImGuiStoragePair(uint _key, float _val) : this(ImGuiPINVOKE.new_ImGuiStoragePair__SWIG_1(_key, _val), true) {
  }

  public ImGuiStoragePair(uint _key, SWIGTYPE_p_void _val) : this(ImGuiPINVOKE.new_ImGuiStoragePair__SWIG_2(_key, SWIGTYPE_p_void.getCPtr(_val)), true) {
  }

}

}
