//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiSliderFlags_ {
  ImGuiSliderFlags_None = 0,
  ImGuiSliderFlags_AlwaysClamp = 1 << 4,
  ImGuiSliderFlags_Logarithmic = 1 << 5,
  ImGuiSliderFlags_NoRoundToFormat = 1 << 6,
  ImGuiSliderFlags_NoInput = 1 << 7,
  ImGuiSliderFlags_WrapAround = 1 << 8,
  ImGuiSliderFlags_InvalidMask_ = 0x7000000F
}

}
