//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiStyleVar_ {
  ImGuiStyleVar_Alpha,
  ImGuiStyleVar_DisabledAlpha,
  ImGuiStyleVar_WindowPadding,
  ImGuiStyleVar_WindowRounding,
  ImGuiStyleVar_WindowBorderSize,
  ImGuiStyleVar_WindowMinSize,
  ImGuiStyleVar_WindowTitleAlign,
  ImGuiStyleVar_ChildRounding,
  ImGuiStyleVar_ChildBorderSize,
  ImGuiStyleVar_PopupRounding,
  ImGuiStyleVar_PopupBorderSize,
  ImGuiStyleVar_FramePadding,
  ImGuiStyleVar_FrameRounding,
  ImGuiStyleVar_FrameBorderSize,
  ImGuiStyleVar_ItemSpacing,
  ImGuiStyleVar_ItemInnerSpacing,
  ImGuiStyleVar_IndentSpacing,
  ImGuiStyleVar_CellPadding,
  ImGuiStyleVar_ScrollbarSize,
  ImGuiStyleVar_ScrollbarRounding,
  ImGuiStyleVar_GrabMinSize,
  ImGuiStyleVar_GrabRounding,
  ImGuiStyleVar_TabRounding,
  ImGuiStyleVar_TabBorderSize,
  ImGuiStyleVar_TabBarBorderSize,
  ImGuiStyleVar_TabBarOverlineSize,
  ImGuiStyleVar_TableAngledHeadersAngle,
  ImGuiStyleVar_TableAngledHeadersTextAlign,
  ImGuiStyleVar_ButtonTextAlign,
  ImGuiStyleVar_SelectableTextAlign,
  ImGuiStyleVar_SeparatorTextBorderSize,
  ImGuiStyleVar_SeparatorTextAlign,
  ImGuiStyleVar_SeparatorTextPadding,
  ImGuiStyleVar_COUNT
}

}
