//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ImGuiSelectionRequest : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImGuiSelectionRequest(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImGuiSelectionRequest obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImGuiSelectionRequest obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImGuiSelectionRequest() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImGuiPINVOKE.delete_ImGuiSelectionRequest(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ImGuiSelectionRequestType Type {
    set {
      ImGuiPINVOKE.ImGuiSelectionRequest_Type_set(swigCPtr, (int)value);
    } 
    get {
      ImGuiSelectionRequestType ret = (ImGuiSelectionRequestType)ImGuiPINVOKE.ImGuiSelectionRequest_Type_get(swigCPtr);
      return ret;
    } 
  }

  public bool Selected {
    set {
      ImGuiPINVOKE.ImGuiSelectionRequest_Selected_set(swigCPtr, value);
    } 
    get {
      bool ret = ImGuiPINVOKE.ImGuiSelectionRequest_Selected_get(swigCPtr);
      return ret;
    } 
  }

  public sbyte RangeDirection {
    set {
      ImGuiPINVOKE.ImGuiSelectionRequest_RangeDirection_set(swigCPtr, value);
    } 
    get {
      sbyte ret = ImGuiPINVOKE.ImGuiSelectionRequest_RangeDirection_get(swigCPtr);
      return ret;
    } 
  }

  public long RangeFirstItem {
    set {
      ImGuiPINVOKE.ImGuiSelectionRequest_RangeFirstItem_set(swigCPtr, value);
    } 
    get {
      long ret = ImGuiPINVOKE.ImGuiSelectionRequest_RangeFirstItem_get(swigCPtr);
      return ret;
    } 
  }

  public long RangeLastItem {
    set {
      ImGuiPINVOKE.ImGuiSelectionRequest_RangeLastItem_set(swigCPtr, value);
    } 
    get {
      long ret = ImGuiPINVOKE.ImGuiSelectionRequest_RangeLastItem_get(swigCPtr);
      return ret;
    } 
  }

  public ImGuiSelectionRequest() : this(ImGuiPINVOKE.new_ImGuiSelectionRequest(), true) {
  }

}

}
