//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiHoveredFlags_ {
  ImGuiHoveredFlags_None = 0,
  ImGuiHoveredFlags_ChildWindows = 1 << 0,
  ImGuiHoveredFlags_RootWindow = 1 << 1,
  ImGuiHoveredFlags_AnyWindow = 1 << 2,
  ImGuiHoveredFlags_NoPopupHierarchy = 1 << 3,
  ImGuiHoveredFlags_AllowWhenBlockedByPopup = 1 << 5,
  ImGuiHoveredFlags_AllowWhenBlockedByActiveItem = 1 << 7,
  ImGuiHoveredFlags_AllowWhenOverlappedByItem = 1 << 8,
  ImGuiHoveredFlags_AllowWhenOverlappedByWindow = 1 << 9,
  ImGuiHoveredFlags_AllowWhenDisabled = 1 << 10,
  ImGuiHoveredFlags_NoNavOverride = 1 << 11,
  ImGuiHoveredFlags_AllowWhenOverlapped = ImGuiHoveredFlags_AllowWhenOverlappedByItem|ImGuiHoveredFlags_AllowWhenOverlappedByWindow,
  ImGuiHoveredFlags_RectOnly = ImGuiHoveredFlags_AllowWhenBlockedByPopup|ImGuiHoveredFlags_AllowWhenBlockedByActiveItem|ImGuiHoveredFlags_AllowWhenOverlapped,
  ImGuiHoveredFlags_RootAndChildWindows = ImGuiHoveredFlags_RootWindow|ImGuiHoveredFlags_ChildWindows,
  ImGuiHoveredFlags_ForTooltip = 1 << 12,
  ImGuiHoveredFlags_Stationary = 1 << 13,
  ImGuiHoveredFlags_DelayNone = 1 << 14,
  ImGuiHoveredFlags_DelayShort = 1 << 15,
  ImGuiHoveredFlags_DelayNormal = 1 << 16,
  ImGuiHoveredFlags_NoSharedDelay = 1 << 17
}

}
