//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class ImGuiTableSortSpecs : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImGuiTableSortSpecs(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImGuiTableSortSpecs obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ImGuiTableSortSpecs obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ImGuiTableSortSpecs() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImGuiPINVOKE.delete_ImGuiTableSortSpecs(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ImGuiTableColumnSortSpecs Specs {
    set {
      ImGuiPINVOKE.ImGuiTableSortSpecs_Specs_set(swigCPtr, ImGuiTableColumnSortSpecs.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ImGuiPINVOKE.ImGuiTableSortSpecs_Specs_get(swigCPtr);
      ImGuiTableColumnSortSpecs ret = (cPtr == global::System.IntPtr.Zero) ? null : new ImGuiTableColumnSortSpecs(cPtr, false);
      return ret;
    } 
  }

  public int SpecsCount {
    set {
      ImGuiPINVOKE.ImGuiTableSortSpecs_SpecsCount_set(swigCPtr, value);
    } 
    get {
      int ret = ImGuiPINVOKE.ImGuiTableSortSpecs_SpecsCount_get(swigCPtr);
      return ret;
    } 
  }

  public bool SpecsDirty {
    set {
      ImGuiPINVOKE.ImGuiTableSortSpecs_SpecsDirty_set(swigCPtr, value);
    } 
    get {
      bool ret = ImGuiPINVOKE.ImGuiTableSortSpecs_SpecsDirty_get(swigCPtr);
      return ret;
    } 
  }

  public ImGuiTableSortSpecs() : this(ImGuiPINVOKE.new_ImGuiTableSortSpecs(), true) {
  }

}

}
