//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiSelectableFlags_ {
  ImGuiSelectableFlags_None = 0,
  ImGuiSelectableFlags_NoAutoClosePopups = 1 << 0,
  ImGuiSelectableFlags_SpanAllColumns = 1 << 1,
  ImGuiSelectableFlags_AllowDoubleClick = 1 << 2,
  ImGuiSelectableFlags_Disabled = 1 << 3,
  ImGuiSelectableFlags_AllowOverlap = 1 << 4,
  ImGuiSelectableFlags_Highlight = 1 << 5
}

}
