//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiChildFlags_ {
  ImGuiChildFlags_None = 0,
  ImGuiChildFlags_Borders = 1 << 0,
  ImGuiChildFlags_AlwaysUseWindowPadding = 1 << 1,
  ImGuiChildFlags_ResizeX = 1 << 2,
  ImGuiChildFlags_ResizeY = 1 << 3,
  ImGuiChildFlags_AutoResizeX = 1 << 4,
  ImGuiChildFlags_AutoResizeY = 1 << 5,
  ImGuiChildFlags_AlwaysAutoResize = 1 << 6,
  ImGuiChildFlags_FrameStyle = 1 << 7,
  ImGuiChildFlags_NavFlattened = 1 << 8
}

}
