//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum ImGuiInputTextFlags_ {
  ImGuiInputTextFlags_None = 0,
  ImGuiInputTextFlags_CharsDecimal = 1 << 0,
  ImGuiInputTextFlags_CharsHexadecimal = 1 << 1,
  ImGuiInputTextFlags_CharsScientific = 1 << 2,
  ImGuiInputTextFlags_CharsUppercase = 1 << 3,
  ImGuiInputTextFlags_CharsNoBlank = 1 << 4,
  ImGuiInputTextFlags_AllowTabInput = 1 << 5,
  ImGuiInputTextFlags_EnterReturnsTrue = 1 << 6,
  ImGuiInputTextFlags_EscapeClearsAll = 1 << 7,
  ImGuiInputTextFlags_CtrlEnterForNewLine = 1 << 8,
  ImGuiInputTextFlags_ReadOnly = 1 << 9,
  ImGuiInputTextFlags_Password = 1 << 10,
  ImGuiInputTextFlags_AlwaysOverwrite = 1 << 11,
  ImGuiInputTextFlags_AutoSelectAll = 1 << 12,
  ImGuiInputTextFlags_ParseEmptyRefVal = 1 << 13,
  ImGuiInputTextFlags_DisplayEmptyRefVal = 1 << 14,
  ImGuiInputTextFlags_NoHorizontalScroll = 1 << 15,
  ImGuiInputTextFlags_NoUndoRedo = 1 << 16,
  ImGuiInputTextFlags_CallbackCompletion = 1 << 17,
  ImGuiInputTextFlags_CallbackHistory = 1 << 18,
  ImGuiInputTextFlags_CallbackAlways = 1 << 19,
  ImGuiInputTextFlags_CallbackCharFilter = 1 << 20,
  ImGuiInputTextFlags_CallbackResize = 1 << 21,
  ImGuiInputTextFlags_CallbackEdit = 1 << 22
}

}
