//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum TextureAccess {
  TA_READ = 0x01,
  TA_WRITE = 0x10,
  TA_READ_WRITE = TA_READ|TA_WRITE
}

}
