//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum TextureAddressingMode : byte {
  TAM_WRAP,
  TAM_MIRROR,
  TAM_CLAMP,
  TAM_BORDER
}

}
