//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum VertexElementSemantic : byte {
  VES_POSITION = 1,
  VES_BLEND_WEIGHTS = 2,
  VES_BLEND_INDICES = 3,
  VES_NORMAL = 4,
  VES_COLOUR = 5,
  VES_COLOUR2 = 6,
  VES_TEXTURE_COORDINATES = 7,
  VES_BINORMAL = 8,
  VES_TANGENT = 9,
  VES_VERTEX_ID = 10,
  VES_COUNT = 10,
  VES_DIFFUSE = VES_COLOUR,
  VES_SPECULAR = VES_COLOUR2
}

}
