//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum VertexAnimationType : byte {
  VAT_NONE = 0,
  VAT_MORPH = 1,
  VAT_POSE = 2
}

}
